backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

    
media_folder: static/img
public_folder: /img

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "landingPage"
        fields:
          - {label: "Template Key", name: templateKey, widget: "hidden", default: "landing-page"}
          - {label: "Title", name: title, widget: string, default: "Do something"}
          - {label: "Sub Title", name: subtitle, widget: string}
          - {label: "About Cards", name: cardsIcon, widget: object, fields: [
            {label: "Title", name: cardTitle, widget: string},
            {label: "Cards", name: cardsIcon, widget: list, fields: [
              {label: "Icon", name: icon, widget: string },
              {label: "Title", name: title, widget: string },
              {label: "Paragraph", name: paragraph, widget: markdown }
            ]}
          ]}
          - {label: "Paragraph Section", name: paragraphSection, widget: object, fields: [
              {label: "Vertical Title", name: vertialTitle, widget: string },
              {label: "Paragraph Title", name: paragraphTitle, widget: string },
              {label: "Paragraph Sub Title", name: subTitle, widget: string },
              {label: "Paragraph", name: paragraph, widget: markdown }
          ]}
          - {label: "Imaged Cards", name: imgCards, widget: object, fields: [
            {label: " Title", name: imgCardTitle, widget: string },
            {label: "Cards", name: cards, widget: list, fields: [
              {label: "Image", name: img, widget: image },
              {label: "Title", name: title, widget: string },
              {label: "Paragraph", name: paragraph, widget: markdown }             
            ]}
          ]}
          - {label: "Contact", name: contact, widget: object, fields: [
              {label: "Phone", name: phone, widget: string },
              {label: "Address", name: address, widget: string },           
              {label: "House", name: hours, widget: string },
              {label: "Email", name: email, widget: string } 
          ]}
      